version: '3'
services:
  squoosh:
    image: dko0/squoosh:1.12.0
    container_name: ${CONTAINER_NAME}
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    restart: unless-stopped
    networks:
      - 1panel-network
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true